twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    # globals: 
    #     categories: $this->getDoctrine()->getRepository(Categorie::class)->findAll()
    #     articles: $this->getDoctrine()->getRepository(Article::class)->findAll(); 